print("Ciao!")
nome = input("Come vuoi chiamare il tuo personaggio? ")
print()
print("In questo gioco dovrai fare delle scelte per",nome,"; per scegliere la tua mossa non dovrai fare altro che scrivere 1 o 2, a seconda della scelta che ritieni piu' giusta, e schiacciare il tasto invio.")
print("Devi riuscire a portare a casa, sano e salvo,",nome,"che non si ricorda come si chiama e non sa dove si trova.")
print("Ricorda che le parentesi graffe contengono i pensieri di " +nome+ "!")
print()
print("Ciao,",nome,"e' in una strada buia davanti ad una pizzeria ed ha un dolore pazzesco alla testa.")
print("Non ha ne' il portafogli ne' i documenti.")
print()
print("~~~~~")
print("{Cosa faccio adesso? Dove vado?}")
print("1. Entri nella pizzeria.")
print("2. Prosegui avanti e percorri la strada .")
print("~~~~~")
risposta1 = input()
print()
risposta5 = "0"
while risposta1 != "1" and risposta1 != "2":
	print("Hai inserito un'opzione non valida, riprova inserendo 1 o 2.")
	risposta1 = input()
print()
if risposta1 != "1":
	print("Procedi avanti, ma poi ti accorgi di uno strano gruppetto di fianco alla pizzeria. Intimorito, decidi di entrarci.")
x = "1"
print("Entri nella pizzeria, ti guardi intorno e cerchi il pizzaiolo.")
print("Lo intravedi alla cassa, sembra molto impegnato ma provi lo stesso a parlargli.")
print(nome+ ": <<Buonasera...>>")
print("Non fai in tempo a parlare che il pizzaiolo ti interrompe:")
print("<<Ciao", nome,", amico mio! La tua pizza di prima non ti e' bastata?>>")
print()
print("~~~~~")
print("{E adesso? Cosa gli dico?}")
print("1. Si, la pizza di prima... Sono cosi' pieno!")
print("2. No, ho una fame terribile! Di che pizza stai parlando?")
print("~~~~~")
risposta3 = input()
print()
while risposta3 != "1" and risposta3 != "2":
	print("Hai inserito un'opzione non valida, riprova inserendo 1 o 2.")
	risposta3 = input()
if risposta3 == "1":
	print(nome+ ": <<Si... La pizza di prima, sono cosi' pieno, non riuscirei piu' a mangiare niente.>>")
	print("<<Va bene, niente pizza. Ci siamo divertiti da matti sta sera eh...")
	print("...Comunque, ti serve qualcosa?>>")
	print()
	print("~~~~~")
	print("{Come rispondo? Gli chiedo se ha visto il mio portafogli?}")
	print("1. Hai visto il mio portafogli?")
	print("2. Non ho bisogno di nulla ero passato solo a salutarti.")
	print("~~~~~")
	risposta4 = input()
	print()
	while risposta4 != "1" and risposta4 != "2":
		print("Hai inserito un'opzione non valida, riprova inserendo 1 o 2")
		risposta4 = input()
	if risposta4 == "1":
		print(nome+ ": <<In effetti dovrei farti una domanda... Per caso hai visto il mio portafogli in giro?>>")
		print("<<Ah si giusto, hai lasciato tutto qui ed io ho conservato tutto, un secondo e riavrai i tuoi beni...>>")
		print("Mentre aspetti ti guardi intorno e noti una foto...")
		print("...nella foto c'e' scritto: 'al mio caro amico Sergio da",nome, ".'")
		print("{E' lo stesso nome che ha pronunciato il pizzaiolo salutandomi. Vuol dire che quello affianco al pizzaiolo sono io e a quanto pare sono un amico di Paolo, il pizzaiolo!}")
		print("Arriva Sergio e ti dice di stare piu' attento alle tue cose...")	
		print("Quindi lo ringrazi, metti le chiavi in tasca e felicissimo apri il tuo portafogli, guardi la tua carta di identita' e noti che abiti a Roma in via 'ARCO DELLA FONTANELLA' al civico n.41")
		print("C'e' solo un piccolo problema: non ti ricordi dove tu sia! E non sai dove si trova la via! Cosi' esci dal locale, noti una bellissima donna che e' prossima ad entrare in macchina.")
		print()
		print("~~~~~")
		print("{Cosa faccio, ci provo? Sono cosi' indeciso...}")
		print("1. Le chiedi il numero di telefono.")
		print("2. Le chiedi dove si trova via ARCO DELLA FONTANELLA.")
		print("~~~~~")
		risposta5 = input()
		print()
		while risposta5 != "1" and risposta5 != "2":
			print("Hai inserito un'opzione non valida, riprova inserendo 1 o 2.")
			risposta5 = input()
		if risposta5 == "1":
			print(nome+ ": <<Salve. Io mi chiedevo se... ehm... ti va di darmi il tuo numero di telefono? Cosi' magari ci incontriamo, qualche volta...>>")
			print("Lei ti guarda nota la tua straordinaria bellezza e ti da il suo numero di telefono!")
			print("....")
			print("Rimani stupito da quanto sia stato facile avere il numero di quella splendida donna. Ah, gia' che ci sei...")
		print("Le chiedi dove si trovava la via ARCO DELLA FONTANELLA.")
		print("Lei ti dice dove si trova la via, la saluti e te ne vai.")
	
	else:
		print(nome+": <<Non ho bisogno di niente grazie... Ero passato solo a salutarti.>>")
		print("<<Ah ok, prima che tu te ne vada, quando te ne sei andato ti sei dimenticato i tuoi oggetti personali qui. Vado a prenderli.>>")
		print()
		print("DOPO UN PO' DI TEMPO...")
		input()
		print("<<Rieccoti tutto, portafogli e chiavi della macchina compresi. La prossima volta stai piu' attento pero'...>>")
		print(nome+ ": <<Grazie ancora, non so come avrei fatto senza di te! Ciao!>>")
		print("Esci dalla pizzeria, e ti ritrovi nella strada buia, dove tutto e' cominciato.")
else:
	x = "2"
	print(nome+": <<No! Ho una fame terribile! Ma... Di che pizza stai parlando?>>")
	print("<<Ne desideri un'altra? Ok... Sempre la solita pizza, quindi?>>")
	print(nome+": <<Si, una bella 4 stagioni... Non ci vedo dalla fame!>>")
	print("<<Perfetto! Una 4 stagioni! Per te offre la casa, amico mio!")
	print()
	print("Mentre aspetti ti guardi intorno e noti una foto...")
	print("...nella foto c'e' scritto: 'al mio caro amico Sergio da",nome, ".'")
	print("{E' lo stesso nome che ha pronunciato il pizzaiolo salutandomi. Cio' vuol dire che io sono" ,nome, "ed a quanto pare sono un amico di Sergio, il pizzaiolo!}")
	print()
	print("DOPO 5 MINUTI")
	input()
	print("<<" +nome+ ", la pizza e' pronta!>>")
	print("Vuoi qualche bevanda per accompagnare la pizza,", nome+ "?")
	print()
	print("~~~~~")
	print("{Cosa prendo? Mmm...}")
	print("1. Vodka.")
	print("2. Acqua.")
	print("3. Birra.")
	print("4. Coca Cola.")
	print("5. Vino.")
	print("6. Whisky")
	print("~~~~~")
	risposta7 = input()
	print()
	while risposta7 != "1" and risposta7 != "2" and risposta7 != "3" and risposta7 != "4" and risposta7 != "5" and risposta7 != "6":
		print("Hai inserito un'opzione non valida, riprova inserendo 1, 2, 3, 4, 5 o 6.")
		risposta7 = input()
	if risposta7 == "1" or risposta7 == "3" or risposta7 == "5" or risposta7 == "6":
		print(nome+ ": <<Vorrei questa, grazie>>")
		print("<<Arriva subito! Eccoti>>")
		print("<<Ah! Gia' che ci sono, ne approfitto per restituirti i tuoi beni personali, portafogli e chiavi della macchina compresi! Stai piu' attento pero' eh...>>")
		print()
		print("Una volta finito di mangiare, ringrazi Sergio, esci dalla pizzeria, un po' turbolento per aver bevuto troppo, e cerchi la tua macchina.")
		print("Non ricordantoti quale sia la tua auto, la apri a distanza con le chiavi,la riconosci, ci entri e controlli sui tuoi documenti l'indirizzo di casa.")
		print()
		print("~~~~~")
		print("Cosa fai?")
		print("1. Metti in moto la auto e parti.")
		print("2. Controlli se e' tutto a posto.")
		print("~~~~~")
		risposta8 = input()
		print()
		while risposta8 != "1" and risposta8 != "2":
			print("Hai inserito un'opzione non valida, riprova inserendo 1 o 2.")
			risposta8 = input()
		if risposta8 == "1":
			print("Metti in moto la auto, cerchi di partire, ma qualcosa e' andato storto e colpisci la auto davanti a te.")
			print("Casualmente, esce dalla pizzeria un uomo, che, una volta capito che tu gli hai rotto l'auto, corre verso di te.")
			print("Stai cercando di scappare, ma i 2 litri di alcol di prima stanno avendo effetto e ti ritrovi tra le montagne con le caprette di Heidi.")
			print("Nel frattempo, l'uomo arriva ed inizia a prenderti a mazzate, e alla fine muori di trauma cranico.")
			print()
			print("GAME OVER")
			print("Il gioco e' finito perche' il tuo personaggio e' morto.")
		else:
			print("Una volta controllato tutto, parti per raggiungere casa.")
			print("Nel frattempo ti arriva un messaggio dalla tua ex fidanzata, con dei cuoricini alla fine del messaggio!")
			print()
			print("~~~~~")
			print("{Cosa faccio? Magari si vuole rimettere con me...}")
			print("1. Apri e controlli il messaggio.")
			print("2. Ignori il messaggio.")
			print("~~~~~")
			risposta9 = input()
			print()
			while risposta9 != "1" and risposta8 != "2":
				print("Hai inserito un'opzione non valida, riprova inserendo 1 o 2.")
				risposta9 = input()
			if risposta9 == "1":
				print("Apri la chat e leggi che la tua ex si vuole mettere con te! Sei felicissimo e le rispondi subito!")
				print("Purtroppo ti sei distratto dalla guida, e ti sei schiantato contro un albero a grande velocita'. Poco dopo vedi l'ambulanza.")
				print("Ormai e' troppo tardi, l'impatto e' stato troppo forte e i danni troppo gravi... non ce la fai, e alla fine muori.")
				print()
				print("GAME OVER")
				print("Il gioco e' finito perche' il tuo personaggio e' morto.")
			else:
				print("Hai deciso di non leggere il messaggio, ottima scelta! Pero' i 2 litri di alcol si fanno sentire, ti senti male e i tuoi riflessi diminuiscono.")
				print("Vedi una persona che sta attraversando la strada, cerchi di frenare ma ormai e' troppo tardi, investi la persona e la uccidi.")
				print("Casualmente passava da quelle parti la polizia, che, vista tutta la scena, ti ferma e ti arresta .")
				print()
				print("GAME OVER")
				print("Il gioco e' finito perche' il tuo personaggio e' stato arreststo.")
	else:
		print(nome+ ": <<Vorrei questa, grazie>>")
		print("<<Arriva subito! Eccoti>>")
		print("<<Ah! Gia' che ci sono, ne approfitto per restituirti i tuoi beni personali, portafogli e chiavi della macchina compresi! Stai piu' attento pero' eh...>>")
		print()
		print("Una volta finito di mangiare, ringrazi Sergio ed esci dalla pizzeria.")
		print("Decidi di percorrere la strada, ed ad un certo punto incontri un uomo incappucciato con la testa china. Potresti parlargli, ma non ti fidi molto.")
		print()
		print("~~~~~")
		print("{Che cosa devo fare? E' un tipo strano... Potrebbe essere pericoloso... Non saprei.}")
		print("1. Decidi, a malincuore, di parlargli.")
		print("2. Te ne vai, poco fiducioso, e prosegui per la tua strada.")
		print("~~~~~")
		risposta2 = input()
		print()
		while risposta2 != "1" and risposta2 != "2":
			print("Hai inserito un'opzione non valida, riprova inserendo 1 o 2.")
			risposta2 = input()
		if risposta2 == "1" :
			print("Lo chiami, ma lui appena alza il capo rivela una faccia cosi' spaventosa che ti impaurisci e...")
			print()
			print("PREMI INVIO PER SCAPPARE")
			input()
			print("...inizi a scappare!")
		else:
			print("Seguendo il tuo istinto prosegui per la strada, solo la luce di un lampione illumina la tua via.")
		print("Ad un certo punto vedi una macchina avvicinarsi e fermarsi accanto a te. E.... Dall'auto scende un uomo, e ha in mano qualcosa!.")
		print()
		print("PREMI INVIO PER CERCARE DI SCAPPARE")
		input()
		print("...")
		print("{Cosa e' successo? Dove mi trovo? Non ricordo piu' niente... Stavo fuggendo... Si', stavo fuggendo da qualcuno...}")
		print("{... E poi, e poi ho perso i sensi... Sono legato! Come faccio a scappare? Devo trovare un modo per...}")
		print()
		print("PREMI INVIO PER CERCARE DI LIBERARTI")
		input()
		print()
		print("PREMI INVIO PER CERCARE DI LIBERARTI")
		input()
		print("{Niente da fare... Non ci riesco}")
		print("<<Salve! Ti trovi qui, in questo posto, per sapere se morirai, o continuerai a vivere!")
		print("Ti faro' un indovinello, e se risponderai correttamente, ti lasciero' andare, altrimenti, morirai!")
		print("L'indovinello e'...")
		print()
		print("<<Questa cosa tutto divora: uccelli, bestie, alberi e fiori; mastica il ferro e morde l'acciaio; riduce in polvere le rocce piu' dure; uccide i re, distrugge le citta' ed abbatte le piu' alte montagne.>>")
		print("Scrivi la risposta senza maiuscole, senza punteggiatura e senza articoli, esempio: 'acqua' ")
		indovinello = input()
		print()
		print("'" +indovinello+ "' e' la tua risposta definitiva? (inserisci Si oppure No)")
		indovinello2 = input()
		while indovinello2 != "Si" and indovinello2 != "No":
			print("Hai inserito un'opzione non valida, riprova inserendo Si o No.")
			indovinello2 = input()
		if indovinello2 == "No":
			print("Inserisci la nuova risposta: ")
		if indovinello2 == "Si":
			print("<<Complimenti, la risposta giusta e' il tempo! Hai superato l\'indovinello, e percio' ti portero' dove vuoi.>>")
			indovinello = input()
		if indovinello == "tempo":
			print()
			print("<<Complimenti, la risposta giusta e' il tempo! Hai superato l'indovinello, e percio' ti portero' dove vuoi.>>")
			print()
			print("DOPO UN PO' DI TEMPO")
			print()
			print("<<Ecco, ti ho portato dove volevi. Addio.>>")
			print("Finalmente sei davanti a casa, ed entri, dopo tante avventure.")
			print()
			print("Complimenti! Hai finito il gioco! Prova a finirlo in uno degli altri modi!")
		else:
			print("<<La risposta '" +indovinello+ "' non e' giusta! La risposta esatta e' un'altra! E percio' morirai!")
			print()
			print("GAME OVER")
			print("Il gioco e' finito perche' il tuo personaggio e' morto. ")
if x == "1":
	print("Decidi di percorrere la strada, ed ad un certo punto incontri un uomo incappucciato con la testa china. Potresti parlargli, ma non ti fidi molto.")
	print()
	print("~~~~~")
	print("{Che cosa devo fare? E' un tipo strano... Potrebbe essere pericoloso... Non saprei.}")
	print("1. Decidi, a malincuore, di parlargli.")
	print("2. Te ne vai, poco fiducioso, e prosegui per la tua strada.")
	print("~~~~~")
	risposta10 = input()
	print()
	while risposta10 != "1" and risposta10 != "2":
		print("Hai inserito un'opzione non valida, riprova inserendo 1 o 2.")
		risposta10 = input()
	if risposta10 == "1" :  
		print("Lo chiami, ma lui appena alza il capo rivela una faccia cosi' spaventosa che ti impaurisci e...")
		print()
		print("PREMI INVIO PER SCAPPARE")
		input()
		print("...inizi a scappare!")
	else:
		print("Seguendo il tuo istinto prosegui per la strada, solo la luce di un lampione illumina la tua via.")
	print("Stai camminando ormai da troppo tempo, abbastanza da sentire un insopportabile dolore ai piedi.")
	print("Allora alzi lo sguardo e vedi che sei nella via giusta, sei vicino all'obiettivo, ora devi solo raggiungere il civico giusto.")
	print("31...33...35...37...39...e finalmente il 41!!!")
	print()
	print("~~~~~")
	print("{Cosa faccio? Ci sara' qualcuno dentro casa?}")
	print("1. Entri in casa.")
	print("2. Rimani fuori.")
	print("~~~~~")
	risposta6 = input()
	print()
	while risposta6 != "1" and risposta6 != "2":
		print("Hai inserito un'opzione non valida, riprova inserendo 1 o 2.")
		risposta6 = input()
	if risposta6 == "1":
		print("Complimenti hai finito il gioco,",nome," e' tornato a casa!")
		if risposta5 == "1":
			print("E grazie a te ha anche trovato una ragazza!")
			print("Se ti va prova a finire il gioco in uno degli altri modi!!")
	else:
		print("GAME OVER")
		print(nome ,"e' rimasto fuori casa troppe ore, e dato che e' inverno e' morto di ipotermia")
		print("Il gioco e' finito perche' il tuo personaggio e' morto") 
